name: Checkout & Build Pipeline
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions"
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -la
      - run: touch file1
      - run: ls -la
