name: Hello Pipeline
on: 
  push:
    branches:
      - main

jobs:
  hellogit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions"
      - run: echo 'This is my first pipeline'
